### ISSUE TITLE
Tests unitaires

### ISSUE THREAD

**Issue by naegi** [mdl29/panobus#1]
Fonctions à tester : 
*  ~~getRemainingTimes~~
* ~~getStopNames~~
* ~~getRoutes~~
* ~~getDestinations~~
* ~~getRoutesStops~~

**Plus rien à tester pour le moment**

**Comment by Boblecodeur** [comment]
Attention il s'agit de getDestinations et non pas de getdestinations

**Comment by naegi** [comment]
Mettre à jour le test de getVersion (on est plus en bêta)
