### ISSUE TITLE
Décalage

### ISSUE THREAD

**Issue by LeonisCuriosity** [mdl29/panobus#10]
lorsqu'on arrive sur la dernier diapo, il se crée un espace en bas qui décale toutes les pages de (20px et quelques) vers le haut.
Cet écart n'est résorbé que lorsqu'on bidouille la hauteur de la fenêtre ou qu'on se met sur la première page.

**Comment by naegi** [comment]
Corrigé par commit   0da4df4  ? Chez moi oui, je te laisse finir de tester
