### ISSUE TITLE
erreur lors du lancement de ./maketest.sh

### ISSUE THREAD

**Issue by Boblecodeur** [mdl29/panobus#2]
Traceback (most recent call last):
  File "./bibus-test.py", line 3, in <module>
    import bibus
  File "../bibus.py", line 5
    def __init__(self,what:str):
                          ^
SyntaxError: invalid syntax

**Comment by naegi** [comment]
C'est quoi ta version de python ?

**Comment by naegi** [comment]
Il faut lancer python 3.x

**Comment by HS-157** [comment]
C'est ça être sur un système obsolète qui utilise Python2.7 par défaut
