### ISSUE TITLE
Erreur sur certains arrets

### ISSUE THREAD

**Issue by Boblecodeur** [mdl29/panobus#3]
Les arrets comportant des espaces comme "Porte de plouzané, Porte de gouesnou, Porte de guipavas, Port de commerce, etc..." ne sont pas suportés pour l'envoi des données dans l'url.

**Comment by naegi** [comment]
Si tu peux corriger ça vite, moi je peux pas là Import urllib.parse (ou un truc dans le genre) 

Et pour chaque arg rajoute dans les format urllib.parse.urlencode

^^ merci d'avance 





------
Tristan Gouge

**Comment by Benvii** [comment]
Je peux le faire demain soir (mardi soir) si c'est pas urgent. Vu trop tard pour le faire ce soir. 

A+

**Comment by naegi** [comment]
Tant que personne n'utilise le code c'est pas important pour le moment mais ça permet de vite clore l'issueBenjamin tant que t'es là je vais faire un peu de hors sujet mais faudrait faire un cour sur les tests (unitaires... Etc...) parce que je vois que Tristan ne sais pas vraiment comment ça fonctionne (il a pas mis d'assert dans ces tests par exemple) et j'ai de forte présomption pour que seul un ou deux sais ce que c'est et que moins encore les utilise -moi même, j'avoue, c'est le premier code où j'essaye de tester systématiquement, peut être mal qui sais 





------
Tristan Gouge

**Comment by Boblecodeur** [comment]
Je N'ai pas mis dassert car je n'ai pas fini j'ai chercher déjà comment
faire pour gérer les espaces

**Comment by Benvii** [comment]
C'est corrigé j'en ai profité pour refactorer un peu le code, quand je vois la structure des méthodes get* je me dit qu'il y a moyen de factoriser un peu plus ;) 
Je vous laisse gérer le reste.

A+
