### ISSUE TITLE
Problème aléatoire

### ISSUE THREAD

**Issue by Boblecodeur** [mdl29/panobus#4]
Nous avons fait cette après midi le JSON du lycée, avec Léo, il est assez consequent il y 21 arrets...
Lorsqu'on lance le script python, certains arrets sont recupérés lors de certain GET alors qu'au GET suivant il renvoi rien "Bad URI ?".
Je pense qu'il sagit d'une erreur au niveau même de l'API bibus mais ca reste à voir.

**Comment by Boblecodeur** [comment]
Erreur typique:

<code>DEBUG:root:Get data : 
WARNING:root:Bad URI ? : /WIPOD01/Transport/REST/getRemainingTimes?trip_headsign=Plougastel&route_id=8&format=json&stop_name=Donnart
WARNING:root:Bad URI ? : /WIPOD01/Transport/REST/getRemainingTimes?trip_headsign=Hopital+Tromeur&route_id=7&format=json&stop_name=messidou
</code>
<code>
DEBUG:root:Get data : 
WARNING:root:Bad URI ? : /WIPOD01/Transport/REST/getRemainingTimes?trip_headsign=Plougastel&route_id=8&format=json&stop_name=Donnart
WARNING:root:Bad URI ? : /WIPOD01/Transport/REST/getRemainingTimes?trip_headsign=Plougastel&route_id=8&format=json&stop_name=Le+Moult
WARNING:root:Bad URI ? : /WIPOD01/Transport/REST/getRemainingTimes?trip_headsign=Hopital+Tromeur&route_id=7&format=json&stop_name=messidou
WARNING:root:Bad URI ? : /WIPOD01/Transport/REST/getRemainingTimes?trip_headsign=Hopital+Tromeur&route_id=7&format=json&stop_name=st+luc
WARNING:root:Bad URI ? : /WIPOD01/Transport/REST/getRemainingTimes?trip_headsign=Hopital+Tromeur&route_id=7&format=json&stop_name=Kerichen+lycee
</code><code>
DEBUG:root:Get data : 
WARNING:root:Bad URI ? : /WIPOD01/Transport/REST/getRemainingTimes?trip_headsign=Plougastel&route_id=8&format=json&stop_name=Donnart
WARNING:root:Bad URI ? : /WIPOD01/Transport/REST/getRemainingTimes?trip_headsign=Plougastel&route_id=8&format=json&stop_name=Le+Moult
WARNING:root:Bad URI ? : /WIPOD01/Transport/REST/getRemainingTimes?trip_headsign=Plougastel&route_id=8&format=json&stop_name=montaigne
WARNING:root:Bad URI ? : /WIPOD01/Transport/REST/getRemainingTimes?trip_headsign=Hopital+Tromeur&route_id=7&format=json&stop_name=messidou
WARNING:root:Bad URI ? : /WIPOD01/Transport/REST/getRemainingTimes?trip_headsign=Hopital+Tromeur&route_id=7&format=json&stop_name=st+luc
WARNING:root:Bad URI ? : /WIPOD01/Transport/REST/getRemainingTimes?trip_headsign=Hopital+Tromeur&route_id=7&format=json&stop_name=Kerichen+lycee
</code><code>
DEBUG:root:Get data : 
WARNING:root:Bad URI ? : /WIPOD01/Transport/REST/getRemainingTimes?trip_headsign=Plougastel&route_id=8&format=json&stop_name=Donnart
WARNING:root:Bad URI ? : /WIPOD01/Transport/REST/getRemainingTimes?trip_headsign=Plougastel&route_id=8&format=json&stop_name=Le+Moult
WARNING:root:Bad URI ? : /WIPOD01/Transport/REST/getRemainingTimes?trip_headsign=Plougastel&route_id=8&format=json&stop_name=montaigne
WARNING:root:Bad URI ? : /WIPOD01/Transport/REST/getRemainingTimes?trip_headsign=Hopital+Tromeur&route_id=7&format=json&stop_name=messidou
WARNING:root:Bad URI ? : /WIPOD01/Transport/REST/getRemainingTimes?trip_headsign=Hopital+Tromeur&route_id=7&format=json&stop_name=st+luc
WARNING:root:Bad URI ? : /WIPOD01/Transport/REST/getRemainingTimes?trip_headsign=Hopital+Tromeur&route_id=7&format=json&stop_name=Kerichen+lycee
WARNING:root:Bad URI ? : /WIPOD01/Transport/REST/getRemainingTimes?trip_headsign=Hopital+Tromeur&route_id=7&format=json&stop_name=blum
</code><code>
DEBUG:root:Get data : 
WARNING:root:Bad URI ? : /WIPOD01/Transport/REST/getRemainingTimes?trip_headsign=Plougastel&route_id=8&format=json&stop_name=Donnart
WARNING:root:Bad URI ? : /WIPOD01/Transport/REST/getRemainingTimes?trip_headsign=Plougastel&route_id=8&format=json&stop_name=Le+Moult
WARNING:root:Bad URI ? : /WIPOD01/Transport/REST/getRemainingTimes?trip_headsign=Plougastel&route_id=8&format=json&stop_name=montaigne
WARNING:root:Bad URI ? : /WIPOD01/Transport/REST/getRemainingTimes?trip_headsign=Hopital+Tromeur&route_id=7&format=json&stop_name=messidou
WARNING:root:Bad URI ? : /WIPOD01/Transport/REST/getRemainingTimes?trip_headsign=Hopital+Tromeur&route_id=7&format=json&stop_name=st+luc
WARNING:root:Bad URI ? : /WIPOD01/Transport/REST/getRemainingTimes?trip_headsign=Hopital+Tromeur&route_id=7&format=json&stop_name=Kerichen+lycee
WARNING:root:Bad URI ? : /WIPOD01/Transport/REST/getRemainingTimes?trip_headsign=Hopital+Tromeur&route_id=7&format=json&stop_name=blum
WARNING:root:Bad URI ? : /WIPOD01/Transport/REST/getRemainingTimes?trip_headsign=Hopital+Tromeur&route_id=7&format=json&stop_name=mirabeau</code>

**Comment by naegi** [comment]
Une erreur de try except je pense





------
Tristan Gouge

**Comment by naegi** [comment]
Le problème vient de bibus, j'envoie 255 si il n'y a pas de data. Fixé par 48a8dfe5bf1aa4fde156b296e697cd61c724b686
