### ISSUE TITLE
Remarque

### ISSUE THREAD

**Issue by tristanplouz** [mdl29/panobus#5]
Apres quelques tests avec le code arduino, je trouve que la frequence de rafraichissment n'est pas assez elevé. Le bus passe de EN APPROCHE à LOIN, c'est un peu dommage.
Il faudrait rafraichir toutes les 30s je pense.
Qu'en pensez vous?

**Comment by naegi** [comment]
même avec un décompteur côté arduino ?

**Comment by Boblecodeur** [comment]
Comment ça un decompteur? Si c'est faire décrémenté un compteur côté arduino, il vaut mieux réduire l'intervalle d'envoi

**Comment by naegi** [comment]
Bah pendant que le main.py lance echo '["setUpdateInterval","n"]' >
/tmp/bibusPipe avec n le nbr de secondes

**Comment by naegi** [comment]
Mettre le délai dans le json paraît correct pour toi ?

**Comment by tristanplouz** [comment]
Bah on le laisse à 30secondes, je pense que cela suffit
