### ISSUE TITLE
Neopixel sur pc

### ISSUE THREAD

**Issue by naegi** [mdl29/panobus#6]
Je propose de créer une sorte de library vide basé sur l'api de neopixel (au moins ce que l'on utilise) pour que l'on puisse tester le code de ledHandler et compagnie sur pc
Ajouter des tests et des infos de debuggages dans la lib est fortement envisageable je pense
Qu'en pensez vous ?

**Comment by Benvii** [comment]
+1 et pourquoi pas en gros faudrait se baser sur "l'interface" de Adafruit_NeoPixel (qui n'est pas énorme : https://github.com/jgarff/rpi_ws281x/blob/master/python/neopixel.py ).
Mais c'est à mon sens trop complexe pour le relier à des tests unitaires ... sauf si de l'autre coté tu as aussi des jeux de données de test bibus en entrée :) 
Donc se subtituer à l'API Bibus ce qui serait intéressant ça ouvrirait aussi la porte à d'autres API (La Star à Rennes ...) ça nécessite de revoir le code et réfléchir à quelque chose d'ultra modulable (regarder d'autres API).

**Comment by naegi** [comment]
J'y avais pensé, mais j'avais pensé à juste créer un wrapper avec une api
«de base» (d'après ce que l'on utilise) qui sera redéfinie pour chaque api
que l'on ajoute le problème c'est comment passer d'une api à l'autre sans
avoir à modifier le code (j'avais pensé à un = __import__(api name) mais je
trouve ça moche)

Le mar. 9 févr. 2016 12:42 PM, Benjamin BERNARD <notifications@github.com>
a écrit :

> +1 et pourquoi pas en gros faudrait se baser sur "l'interface" de
> Adafruit_NeoPixel (qui n'est pas énorme :
> https://github.com/jgarff/rpi_ws281x/blob/master/python/neopixel.py ).
> Mais c'est à mon sens trop complexe pour le relier à des tests unitaires
> ... sauf si de l'autre coté tu as aussi des jeux de données de test bibus
> en entrée :)
> Donc se subtituer à l'API Bibus ce qui serait intéressant ça ouvrirait
> aussi la porte à d'autres API (La Star à Rennes ...) ça nécessite de revoir
> le code et réfléchir à quelque chose d'ultra modulable (regarder d'autres
> API).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mdl29/panobus/issues/6#issuecomment-181830004>.
>
-- 

------
Gouge Tristan

**Comment by tristanplouz** [comment]
Pour développer le projet il faudrait qu'il soit construit en 3 partie:

- Une partie API avec la gestion des API de Bibus, de la STAR, de KSMA,etc

- Une partie qui traite les infos indépendantes des API et de l'affichage

- Une partie qui gère l'affichage sur les LEDs ou sur un écran

Avec cette structure je pense que le projet sera entièrement modulable et ensuite plus simple à modifier

**Comment by naegi** [comment]
Comme on fait actuellemen j'ai envie de dire
L'issue part en HS j'ouvre une autre
